services:
  flask-server:
    build: .
    container_name: stock-control-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://michael:Lc17ma1a2e17b@postgres-michael:5432/stock_control_db
      - HUBSPOT_TOKEN=${HUBSPOT_TOKEN}
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - network-michael

networks:
  network-michael:
    external: true